
services:
  postgres:
    image: bitnami/postgresql:14
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=forumhub
    volumes:
      - forumhub_pg_data:/bitnami/postgresql

  redis:
    image: bitnami/redis:6
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"
    volumes:
      - "forumhub_redis_data:/bitnami/redis/data"

volumes:
  forumhub_pg_data:
  forumhub_redis_data:
